openapi: 3.2.0
info:
  title: ASCE Hazard Loads API documentation Snow API
  description: This is the API documentation for the ASCE Hazard Loads API.
  version: 1.0.0
servers:
- url: https://api-hazard.asce.org/v1
- url: http://localhost:3000/v1
security:
- ApiKeyAuth: []
tags:
- name: Snow
paths:
  /snow:
    get:
      tags:
      - Snow
      summary: Get snow information
      parameters:
      - name: lat
        in: query
        description: Latitude of the location
        required: true
        schema:
          type: number
          default: 34.921206
      - name: lon
        in: query
        description: Longitude of the location
        required: true
        schema:
          type: number
          default: -118.418998
      - name: standardsVersion
        in: query
        description: Standards version
        required: true
        schema:
          type: string
          enum:
          - 7-10
          - 7-16
          - 7-22
      - name: riskLevel
        in: query
        description: Risk level
        required: true
        schema:
          type: number
          enum:
          - 1
          - 2
          - 3
          - 4
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
      operationId: getSnow
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: token
      in: query
